export const options = {
  type: {
    zh: {
      venue: "場地",
      manpower: "人力資源",
      funding: "資金",
      expertise: "專業",
      network: "人際網絡",
      other: "其他",
    },
    en: {
      venue: "venue",
      manpower: "manpower",
      funding: "funding",
      expertise: "expertise",
      network: "network",
      other: "other",
    }
  },
  manpowerType: {
    zh:{
      individual: "個人",
      group: "團體",
      other: "其他",
    },
    en:{
      individual: "individual",
      group: "group",
      other: "other",
    },
  },
  serviceNature: {
    zh:{
      consultant: "顧問",
      volunteer: "義工",
      partime: "廉職",
      fulltime: "全職",
    },
    en:{
      consultant: "consultant",
      volunteer: "volunteer",
      partime: "partime",
      fulltime: "fulltime",
    },
  },
  projectDuration: {
    zh:{
      undecided: "未決定",
      oneOff: "一次性的計劃",
      inProgress: "進行中的計劃",
    },
    en:{
      undecided: "undecided",
      oneOff: "one off",
      inProgress: "in progress",
    },
  },
  expertiseType: {
    zh:{
      marketing: "市場推廣",
      fundraising: "籌款",
      proposalWriting: "計劃書",
      subjectKnowledge: "行業專業知識",
      socialMedia: "社交媒體",
      website: "網站",
      design: "設計",
      videoEditor: "視頻剪接",
      customerService: "客戶服務",
      photography: "攝影",
      translation: "翻譯",
      financeAndAccounts: "財務/會計",
      impactAssessment: "效益評估",
      sales: "銷售",
      mentoringAndCoaching: "導師",
      counselling: "輔導",
      teaching: "教學",
      eventManagement: "場地管理",
      signLanguageInterpretation: "手語翻譯",
      audioVisualDescription: "視聽說明",
      performance: "表演",
      other: "其他"
    },
    en:{
      marketing: "marketing",
      fundraising: "fundraising",
      proposalWriting: "proposal writing",
      subjectKnowledge: "subject knowledge",
      socialMedia: "social media",
      website: "website",
      design: "design",
      videoEditor: "video editor",
      customerService: "customer service",
      photography: "photography",
      translation: "translation",
      financeAndAccounts: "finance and accounts",
      impactAssessment: "impact assessment",
      sales: "sales",
      mentoringAndCoaching: "mentoring and coaching",
      counselling: "counselling",
      teaching: "teaching",
      eventManagement: "event management",
      signLanguageInterpretation: "sign language interpretation",
      audioVisualDescription: "audio visual description",
      performance: "performance",
      other: "other"
    },
  },
  networkType: {
    zh:{
      foodAndBeverage: "飲食業",
      manufacturing: "製造業",
      customerService: "客戶管理",
      HRAndAdministration: "人力資源/行政",
      construction: "建造業",
      importAndExport: "出入口",
      retail: "零售",
      logistics: "物流(交通，快遞，郵遞，倉庫)",
      financingAndInsurance: "金融及保險",
      realEstate: "地產",
      professional: "專業人士",
      businessServices: "商業服務",
      education: "教育",
      humanHealth: "健康",
      socialWork: "社會服務",
      personalService: "個人服務",
      accommodationAndHospitality: "酒店業",
      informationAndCommunications: "資訊及通訊",
      artsAndCultureAndCreativeIndustry: "藝術/文化/創意",
      other: "其他",
    },
    en:{
      foodAndBeverage: "food and beverage",
      manufacturing: "manufacturing",
      customerService: "customer service",
      HRAndAdministration: "HR and administration",
      construction: "construction",
      importAndExport: "import and export",
      retail: "retail",
      logistics: "logistics",
      financingAndInsurance: "financing and insurance",
      realEstate: "realEstate",
      professional: "professional",
      businessServices: "business services",
      education: "education",
      humanHealth: "human health",
      socialWork: "social work",
      personalService: "personal service",
      accommodationAndHospitality: "accommodation and hospitality",
      informationAndCommunications: "information and communications",
      artsAndCultureAndCreativeIndustry: "arts, culture and creative industry",
      other: "other",
    },
  },
  timeAvailable: {
    zh:{
      weekday: "星期一至五",
      weekend: "週末",
      other: "其他",
    },
    en:{
      weekday: "weekday",
      weekend: "weekend",
      other: "other",
    },
  },
  durationNeededUnit: {
    zh:{
      day: "日",
      hour: "小時",
      week: "星期",
      month: "月",
    },
    en:{
      day: "day",
      hour: "hour",
      week: "week",
      month: "month",
    },
  },
  frequency: {
    zh:{
      oneTime: "一次性",
      always: "經常",
    },
    en:{
      oneTime: "one time",
      always: "always",
    },
  },
  targetGroups: {
    zh:{
      public: "大眾",
      carer: "家長/ 照顧者",
      educator: "教育工作者",
      ngo: "非政府組織",
      employers: "社企",
      businesses: "商業",
      disabilities: "殘疾人士",
    },
    en:{
      public: "public",
      carer: "carer",
      educator: "educator",
      ngo: "ngo",
      employers: "employers",
      businesses: "businesses",
      disabilities: "disabilities",
    },
  },
  targetGroupDisabilities: {
    zh:{
      attentionDeficitHyperactivityDisorder: "注意力不足／過度活躍症",
      intellectualDisability: "智障",
      physicalImpairment: "肢體傷殘",
      visceralDisabilityPersonswithChronicDiseases: "器官殘障／長期病患",
      autism: "自閉症譜系障礙",
      mentalIllnessMoodDisorder: "精神病",
      specificLearningDifficulties: "特殊學習障礙",
      visualImpairment: "視障",
      hearingImpairment: "聽障",
      speechImpairment: "言語障礙",
      other: "其他",
      all: "以上全部",
    },
    en:{
      attentionDeficitHyperactivityDisorder: "attention deficit hyperactivity disorder",
      intellectualDisability: "intellectual disability",
      physicalImpairment: "physical impairment",
      visceralDisabilityPersonswithChronicDiseases: "visceral disability persons with chronic diseases",
      autism: "autism",
      mentalIllnessMoodDisorder: "mentalIllness mood disorder",
      specificLearningDifficulties: "specific learning difficulties",
      visualImpairment: "visual impairment",
      hearingImpairment: "hearing impairment",
      speechImpairment: "speech impairment",
      other: "other",
      all: "all",
    },
  },
  educationLevel: {
    zh:{
      masterOrPostgraduate: "碩士或深造文憑",
      degree: "學士學位",
      nonDegreeTertiary: "副學士或高級文憑",
      schoolCertificate: "中學畢業",
      primaryOrBelow: "小學程度或以下"
    },
    en:{
      masterOrPostgraduate: "master or postgraduate",
      degree: "degree",
      nonDegreeTertiary: "nonDegree tertiary",
      schoolCertificate: "school certificate",
      primaryOrBelow: "primary or below"
    },
  },
  district: {
    zh:{
      centralAndWestern: "中西區",
      eastern: "東區",
      southern: "南區",
      shamShuiPo: "深水埗區",
      kowloonCity: "九龍城區",
      kwunTong: "觀塘區",
      wongTaiSin: "黃大仙區",
      yauTsimMong: "油尖旺區",
      islands: "離島區",
      kwaiTsing: "葵青區",
      north: "北區",
      saiKung: "西貢區",
      shaTin: "沙田區",
      taiPo: "大埔區",
      tsuenWan: "荃灣區",
      tuenMun: "屯門區",
      yuenLong: "元朗區"
    },
    en:{
      centralAndWestern: "Central And Western",
      eastern: "Eastern",
      southern: "Southern",
      shamShuiPo: "Sham Shui Po",
      kowloonCity: "Kowloon City",
      kwunTong: "Kwun Tong",
      wongTaiSin: "Wong Tai Sin",
      yauTsimMong: "Yau Tsim Mong",
      islands: "Islands",
      kwaiTsing: "Kwai Tsing",
      north: "North",
      saiKung: "Sai Kung",
      shaTin: "Sha Tin",
      taiPo: "Tai Po",
      tsuenWan: "Tsuen Wan",
      tuenMun: "Tuen Mun",
      yuenLong: "Yuen Long"
    },
  },
  numberOfConsultantsNeeded: {
    zh:{
      numberOfConsultantsNeeded: "需要顧問人數"
    },
    en:{
      numberOfConsultantsNeeded: "Consultants needed"
    },
  },
  numberOfVolunteersNeeded: {
    zh:{
      numberOfVolunteersNeeded: "需要的義工人數"
    },
    en:{
      numberOfVolunteersNeeded: "Volunteers Needed"
    },
  }
};
