export const options = {
  type: {
    venue: "場地",
    manpower: "人力資源",
    funding: "資金",
    expertise: "專業",
    network: "人際網絡",
    other: "其他",
  },
  manpowerType: {
    individual: "個人",
    group: "團體",
    other: "其他",
  },
  serviceNature: {
    consultant: "顧問",
    volunteer: "義工",
    partime: "廉職",
    fulltime: "全職",
  },
  projectDuration: {
    undecided: "未決定",
    oneOff: "一次性的計劃",
    inProgress: "進行中的計劃",
  },
  expertiseType: {
    marketing: "市場推廣",
    fundraising: "籌款",
    proposalWriting: "計劃書",
    subjectKnowledge: "行業專業知識",
    socialMedia: "社交媒體",
    website: "網站",
    design: "設計",
    videoEditor: "視頻剪接",
    customerService: "客戶服務",
    photography: "攝影",
    translation: "翻譯",
    financeAndAccounts: "財務/會計",
    impactAssessment: "效益評估",
    sales: "銷售",
    mentoringAndCoaching: "導師",
    counselling: "輔導",
    teaching: "教學",
    eventManagement: "場地管理",
    signLanguageInterpretation: "手語翻譯",
    audioVisualDescription: "視聽說明",
    performance: "表演",
    other: "表演",
  },
  networkType: {
    foodAndBeverage: "飲食業",
    manufacturing: "製造業",
    customerService: "客戶管理",
    HRAndAdministration: "人力資源/行政",
    construction: "建造業",
    importAndExport: "出入口",
    retail: "零售",
    logistics: "物流(交通，快遞，郵遞，倉庫)",
    financingAndInsurance: "金融及保險",
    realEstate: "地產",
    professional: "專業人士",
    businessServices: "商業服務",
    education: "教育",
    humanHealth: "健康",
    socialWork: "社會服務",
    personalService: "個人服務",
    accommodationAndHospitality: "酒店業",
    informationAndCommunications: "資訊及通訊",
    artsAndCultureAndCreativeIndustry: "藝術/文化/創意",
    other: "其他",
  },
  timeAvailable: {
    weekday: "星期一至五",
    weekend: "週末",
    other: "其他",
  },
  durationNeededUnit: {
    hour: "小時",
    week: "星期",
    month: "月",
  },
  frequency: {
    oneTime: "一次性",
    always: "經常",
  },
  targetGroups: {
    public: "大眾",
    carer: "家長/ 照顧者",
    educator: "教育工作者",
    ngo: "非政府組織",
    employers: "社企",
    businesses: "商業",
    disabilities: "殘疾人士",
  },
  targetGroupDisabilities: {
    attentionDeficitHyperactivityDisorder: "注意力不足／過度活躍症",
    intellectualDisability: "智障",
    physicalImpairment: "肢體傷殘",
    visceralDisabilityPersonswithChronicDiseases: "器官殘障／長期病患",
    autism: "自閉症譜系障礙",
    mentalIllnessMoodDisorder: "精神病",
    specificLearningDifficulties: "特殊學習障礙",
    visualImpairment: "視障",
    hearingImpairment: "聽障",
    speechImpairment: "言語障礙",
    other: "其他",
    all: "以上全部",
  },
};
