export default {
    name: { en: "Name", zh: "活動名稱" },
    type: { en: "Type", zh: "活動類別" },
    typeOther: { en: "Other", zh: "其他（請註明）" },
    description: { en: "Description", zh: "活動介紹" },
    startDate: { en: "Start Date", zh: "舉辦日期（由）" },
    endDate: { en: "End Date", zh: "舉辦日期（結束）" },
    datetimeRemark: { en: "Remark", zh: "備註" },
    startTime: { en: "Start Time", zh: "時間（由）" },
    endTime: { en: "End Time", zh: "時間 （結束）" },
    venue: { en: "Venue", zh: "場地" },
    freeOrCharge: { en: "Free or Charge", zh: "免費/收費" },
    price: { en: "Price", zh: "費用" },
    submissionDeadline: { en: "Deadline", zh: "截止登記日期" },
    eventManager: { en: "Event Manager", zh: "聯絡活動籌辦人" },
    contactNumber: { en: "Contact Number", zh: "聯絡電話" },
    registerUrl: { en: "Register URL", zh: "報名連結" },
    otherUrl: { en: "Other", zh: "其他連結" },
    banner: { en: "Banner", zh: "活動計劃圖像" },
    stockPhotoId: { en: "Stock Photo", zh: "如需要活動計劃圖像，請在以下類別內選擇" },
    additionalInformation: { en: "Additional Information", zh: "更多資料" },
    remark: { en: "Remark", zh: "備註" },
};